# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"curr_dir_name": "00_core.ipynb",
         "path": "00_core.ipynb",
         "print_competition_data": "00_core.ipynb",
         "train_path": "00_core.ipynb",
         "test_path": "00_core.ipynb",
         "train_pfiles": "00_core.ipynb",
         "test_pfiles": "00_core.ipynb",
         "get_train_df": "00_core.ipynb",
         "train": "00_core.ipynb",
         "train_all": "00_core.ipynb",
         "get_train_pivot": "00_core.ipynb",
         "get_classification_df": "00_core.ipynb",
         "train_multi": "00_core.ipynb",
         "defeat_position": "01_data.ipynb",
         "get_random_idx": "01_data.ipynb",
         "get_perm_imgs_path": "01_data.ipynb",
         "plot_defected_image": "01_data.ipynb",
         "show_defects": "01_data.ipynb",
         "rle_to_mask": "02_preprocessing.ipynb",
         "multi_rle_to_mask": "02_preprocessing.ipynb",
         "img_with_mask": "02_preprocessing.ipynb",
         "create_masks": "02_preprocessing.ipynb",
         "labels_dir": "02_preprocessing.ipynb",
         "get_classification_dls": "03_models.dls.ipynb",
         "get_segmentation_dls": "03_models.dls.ipynb",
         "classes": "03_models.dls.ipynb",
         "get_segmentation_dls_from_df": "03_models.dls.ipynb",
         "DiceMulti": "04_model.metrics.ipynb",
         "dice_kaggle": "04_model.metrics.ipynb",
         "metric": "04_model.metrics.ipynb",
         "models_dir": "05_models.model.ipynb",
         "class_metrics": "05_models.model.ipynb",
         "get_classifier_learner": "05_models.model.ipynb",
         "seg_metrics": "05_models.model.ipynb",
         "get_segmentation_learner": "05_models.model.ipynb"}

modules = ["core.py",
           "data.py",
           "preprocessing.py",
           "models/dls.py",
           "models/metrics.py",
           "models/model.py"]

doc_url = "https://marcomatteo.github.io/steel_segmentation/"

git_url = "https://github.com/marcomatteo/steel_segmentation/tree/master/"

def custom_doc_links(name): return None
