# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"path": "00_core.ipynb",
         "print_competition_data": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://marcomatteo.github.io/steel_segmentation/"

git_url = "https://github.com/marcomatteo/steel_segmentation/tree/master/"

def custom_doc_links(name): return None
