# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['path', 'print_competition_data']

# Cell
from fastai.vision.all import *
from fastai.metrics import *
import fastai
import torch

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import os
from PIL import Image
from collections import Counter, defaultdict

path = Path('data/')

if not path.is_dir():
    path.mkdir(parents=True, exist_ok=True)

# Cell
def print_competition_data(p:Path = path):
    for elem in p.ls():
        print(elem)