# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_preprocessing.ipynb (unless otherwise specified).

__all__ = ['create_masks', 'labels_dir']

# Cell
from .core import *
from .data import *
from fastcore.foundation import *
from fastai.vision.all import *
from PIL import Image
from collections import defaultdict
from matplotlib import pyplot as plt

import pandas as pd
import numpy as np

# Cell
labels_dir = path / "labels"

def create_masks(df: pd.DataFrame):
    """Create the mask files under the `labels_dir`"""
    for img_id in df["ImageId"].tolist():
        img_path = train_path / img_id
        mask = multi_rle_to_mask(img_path)
        im = Image.fromarray(mask)
        im.save(labels_dir/f"{img_path.stem}_P.png")